POST localhost:8084/api/customers
Content-Type: application/json

{
  "firstName": "brian",
  "lastName": "knight",
  "email": "brianKnight@test.com",
  "phoneNumber": "204-922-2361",
  "address": "224 mcdiarmid drive"
}

###