POST http://localhost:8081/api/transactions
Content-Type: application/json

{
  "customerId": 10,
  "amount": 1000.00,
  "fromAccountId": 10,
  "toAccountId": 2,
  "description": "Test transfer",
  "transactionType": "TRANSFER"
}
